

// NOTE: This data has been enriched with company information and a separate saleDiscount field.
export const INITIAL_MEDICINES_DATA: { name: string; company: string; discount: number | null; saleDiscount: number | null; type: string; }[] = [
  { name: 'EZOMOL 20MG CAP', company: 'ABBOT LABORATORIES', discount: null, saleDiscount: 2, type: 'CAP' },
  { name: 'KLARICID-DS SYP', company: 'ABBOT LABORATORIES', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'MOSPEL LOTION', company: 'ABBOT LABORATORIES', discount: null, saleDiscount: 2, type: 'LOTION' },
  { name: 'SURBEX-Z TAB', company: 'ABBOT LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'CITROSODA SAC', company: 'ABBOT LABORATORIES', discount: null, saleDiscount: 0, type: 'SAC' },
  { name: 'ANAFORTAN PLUS TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'ANAFORTAN PLUS INJ', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 5, type: 'INJ' },
  { name: 'AZOMAX 500MG TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AZOMAX SYP', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'REGIX TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'REGIX SYP', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'REGIX DROPS', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'SINAXAMOL TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'SINAXAMOL EXTRA TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'OSNAT-D TAB', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'OSNAT-D SYP', company: 'ALI GOHAR & COMPANY', discount: null, saleDiscount: 2, type: 'SYP' },
  { name: 'VOREN-SR TAB', company: 'ASIAN CONTINENTIAL', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'ASCARD 75 TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ASCARD PLUS TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'BETADERM LOTION', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 0, type: 'LOTION' },
  { name: 'BETADERM-N OINT', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 2, type: 'OINT' },
  { name: 'BETADERM-N CREAM', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 2, type: 'CREAM' },
  { name: 'DIOPLUS 5/80 MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'DIOPLUS 5/160 MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'DIOPLUS 10/160 MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'SCABFREE LOTION', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 0, type: 'LOTION' },
  { name: 'SYNGAB 50MG CAP', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 4, type: 'CAP' },
  { name: 'DISTELGESIC TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 4, type: 'TAB' },
  { name: 'HEALIT OINT', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 3, type: 'OINT' },
  { name: 'MEROL 25MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'MEROL 50MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'MEROL 100MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'SCABION LOTION', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 1, type: 'LOTION' },
  { name: 'VIGLIP 50/500MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'VIGLIP-M 50/850MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'VIGLIP-M 50/1000MG TAB', company: 'ACTO LABORATORIES', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'CIPOCAIN DROPS', company: 'BARRETT HODHSON', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'CIPOTIC-D DROPS', company: 'BARRETT HODHSON', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'CIPOTIC PLUS DROPS', company: 'BARRETT HODHSON', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'DEXIMOX DROPS', company: 'BARRETT HODHSON', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'DOMEL TAB', company: 'BARRETT HODHSON', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AMOXIL 125MG SYP', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'AMOXIL FORT SYP', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'AMOXIL DROPS', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'DROPS' },
  { name: 'AMOXIL 500MG CAP', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'AUGMENTIN 100MG TAB', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AUGMENTIN 625MG TAB', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AUGMENTIN 375MG TAB', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AUGMENTIN SYP', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'PANADOL TAB', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'PANADOL EXTRA', company: 'BEECHAM PHARMA', discount: null, saleDiscount: 0, type: 'OTHER' },
  { name: 'CALAMOX 1GRAM TAB', company: 'BOSCH PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'CALAMOX 625MG TAB', company: 'BOSCH PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'CALAMOX 156.25 SYP', company: 'BOSCH PHARMA', discount: null, saleDiscount: 2, type: 'SYP' },
  { name: 'CALAMOX-DS SYP', company: 'BOSCH PHARMA', discount: null, saleDiscount: 2, type: 'SYP' },
  { name: 'GETRYL 4MG TAB', company: 'BOSCH PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'GABICA 50MG', company: 'BOSCH PHARMA', discount: null, saleDiscount: 0, type: 'OTHER' },
  { name: 'TORADOL INJ', company: 'BOSCH PHARMA', discount: null, saleDiscount: 7, type: 'INJ' },
  { name: 'CEBOSH SYP', company: 'BROOKS PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'QBAL INJ', company: 'BROOKS PHARMA', discount: null, saleDiscount: 12, type: 'INJ' },
  { name: 'QBAL TAB', company: 'BROOKS PHARMA', discount: null, saleDiscount: 12, type: 'TAB' },
  { name: 'TENZO 4.5 INJ', company: 'BROOKS PHARMA', discount: null, saleDiscount: 9, type: 'INJ' },
  { name: 'TENZO 2.5INJ', company: 'BROOKS PHARMA', discount: null, saleDiscount: 9, type: 'INJ' },
  { name: 'PHLOGIN INJ', company: 'BROOKS PHARMA', discount: null, saleDiscount: 10, type: 'INJ' },
  { name: 'PHLOGIN SR CAP', company: 'BROOKS PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'PHLOGIN 50MG CAP', company: 'BROOKS PHARMA', discount: null, saleDiscount: 1, type: 'CAP' },
  { name: 'NOCLOT 75MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'ONCE-A-DAY TAB (MEN)', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'ONCE-A-DAY TAB (WOMEN)', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'PULMANOL SYP', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 5, type: 'SYP' },
  { name: 'SITA 100MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAMET 50/1000MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAMET 50/850MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAMET 50/500MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'MAGNETT 400MG TAB', company: 'CONTINENTIAL PHARMA-F-E', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'ACNEEZ BAR', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 6, type: 'BAR' },
  { name: 'ACNEEZ CREAM', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 6, type: 'CREAM' },
  { name: 'DICLORAN 50MG TAB', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'GABAPIL 75MG TAB', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'G.T.N OINT', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 6, type: 'OINT' },
  { name: 'LAZMA SMALL CREAM', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 18, type: 'CREAM' },
  { name: 'LAZMA LARGE CREAM', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 18, type: 'CREAM' },
  { name: 'OXIDIL 2G INJ', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'NEUROMET INJ', company: 'DISPENSING ITEMS', discount: null, saleDiscount: 1, type: 'INJ' },
  { name: 'OMEGA 20MG CAP', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: 3, type: 'CAP' },
  { name: 'OMEGA 40MG CAP', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: 1, type: 'CAP' },
  { name: 'XOVOR TAB', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'XOVOR-DIU TAB', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ORLIS 120MG CAP', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: 2, type: 'CAP' },
  { name: 'HYDROZOLE CREAM', company: 'GLAXO-WELLCOME', discount: null, saleDiscount: 0, type: 'CREAM' },
  { name: 'VENTOLIN SOLUTION', company: 'GLAXO-WELLCOME', discount: null, saleDiscount: 0, type: 'SOLUTION' },
  { name: 'MYOLAX 4MG TAB', company: 'GENETICS PHARMA', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'PROLEXA 10MG TAB', company: 'GENETICS PHARMA', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'GABICA 75MG', company: 'GETZ PHARMA', discount: null, saleDiscount: 0, type: 'OTHER' },
  { name: 'RISEK INJ', company: 'GETZ PHARMA', discount: null, saleDiscount: 2, type: 'INJ' },
  { name: 'MONTIGET 10MG TAB', company: 'GETZ PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'PELTON-V TAB', company: 'GLOBAL PHARMACEUTICALS', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'COLIC SYP', company: 'HARBAL MIX MEDICINE', discount: null, saleDiscount: 4, type: 'SYP' },
  { name: 'DANZEN-DS TAB', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'DANZEN TAB', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'COMBIVAIR 400MG CAP', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'COMBIVAIR 200MG CAP', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 1, type: 'CAP' },
  { name: 'KESTIN 10MG TAB', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SIKILEX DROPS', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 2, type: 'DROPS' },
  { name: 'ULSANIC SYP', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'KINZ 10MG INJ', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'KINZ 20MG INJ', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 7, type: 'INJ' },
  { name: 'OMICIN 600MG INJ', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 4, type: 'INJ' },
  { name: 'OMICIN 300MG INJ', company: 'HIGHNOON PHARMA', discount: null, saleDiscount: 4, type: 'INJ' },
  { name: 'ARIA TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 15, type: 'TAB' },
  { name: 'ARIA SYP', company: 'HILTON PHARMA', discount: null, saleDiscount: 9, type: 'SYP' },
  { name: 'INDROP-D INJ', company: 'HILTON PHARMA', discount: null, saleDiscount: 8, type: 'INJ' },
  { name: 'CITANEW 10MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'CITANEW 5MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'HILGAS SYP', company: 'HILTON PHARMA', discount: null, saleDiscount: 2, type: 'SYP' },
  { name: 'SITAGLU MET 50/850MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAGLU MET 50/1000MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAGLU 50MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SITAGLU 100MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'COFERB DROFS', company: 'HILTON PHARMA', discount: null, saleDiscount: 1, type: 'DROPS' },
  { name: 'COFERB SYP', company: 'HILTON PHARMA', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'COFERB PLUS SYP', company: 'HILTON PHARMA', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'ZEEGAB 100MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'ZEEGAB 75MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'ZEEGAB 25MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'XOBIX 7.5MG TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'TENORMIN 25MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'TENORMIN 50MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'TENORMIN 100MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ZESTRIL 10MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ZESTRIL 5MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'SYNFLEX 550MG TAB', company: 'I.C.I PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'DYCLO 50MG TAB', company: 'INDUS PHARMA', discount: null, saleDiscount: 5, type: 'TAB' },
  { name: 'DYCLO 75MG INJ', company: 'INDUS PHARMA', discount: null, saleDiscount: 5, type: 'INJ' },
  { name: 'MOTILIUM TAB', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'MOTILIUM SYP', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'IMODIUM CAP', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'STUGERAN FORT TAB', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'STUGERAN TAB', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'SIBILIUM CAP', company: 'JANSSEN PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'RELEXIN TAB', company: 'MACTER PHARMA', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'COBALMIN TAB', company: 'MACTER PHARMA', discount: null, saleDiscount: 18, type: 'TAB' },
  { name: 'COBALMIN INJ', company: 'MACTER PHARMA', discount: null, saleDiscount: 18, type: 'INJ' },
  { name: 'ENFLOR SAC', company: 'MARTIN DOW PHARMA', discount: null, saleDiscount: 1, type: 'SAC' },
  { name: 'CONCOR2.5MG TAB', company: 'MARCK MARKER', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'GLUCOPHAGE XR 750MG TAB', company: 'MARCK MARKER', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'GLUCOPHAGE XR 500MG TAB', company: 'MARCK MARKER', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'GLUCOVANCE 5/500MG TAB', company: 'MARCK MARKER', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ACEFYL 125 SYP', company: 'NABIQASIM PHARMA', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'ACEFYL COUGH SYP', company: 'NABIQASIM PHARMA', discount: null, saleDiscount: 4, type: 'SYP' },
  { name: 'CLOBIDERM CREAM', company: 'NOORSTEFEL LABORATORIES', discount: null, saleDiscount: 0, type: 'CREAM' },
  { name: 'EXTO 10MG TAB', company: 'NOORSTEFEL LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'EXTO 20MG TAB', company: 'NOORSTEFEL LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'CALCIUM-P SYP', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: 6, type: 'SYP' },
  { name: 'LONACART INJ', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: 2, type: 'INJ' },
  { name: 'ZAFNOL 50MG TAB', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'ZODIP TAB', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'ONSET SYP', company: 'PHARMEDIC LABORATORIES', discount: null, saleDiscount: 1, type: 'SYP' },
  { name: 'ONSET TAB', company: 'PHARMEDIC LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'DARVIN TAB', company: 'PHARMEDIC LABORATORIES', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AZIT CAP', company: 'RAAZEE PHARMA', discount: null, saleDiscount: 5, type: 'CAP' },
  { name: 'AZIT SYP', company: 'RAAZEE PHARMA', discount: null, saleDiscount: 7, type: 'SYP' },
  { name: 'TEXCOL-DM SYP', company: 'RAAZEE PHARMA', discount: null, saleDiscount: 13, type: 'SYP' },
  { name: 'DISPRIN TAB', company: 'RECKET & COLMAN', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'PROVATE-G CREAM', company: 'SAFRON PHARMA', discount: null, saleDiscount: 2, type: 'CREAM' },
  { name: 'PROVATE-G OINT', company: 'SAFRON PHARMA', discount: null, saleDiscount: 2, type: 'OINT' },
  { name: 'TERBISIL 250MG TAB', company: 'SAFRON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'TERBISIL 125MG TAB', company: 'SAFRON PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'ACTIM 5MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AZITMA 250MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'AZITMA 500MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'BISLARI TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'BISLARI INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: '2SUM 2G INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: '2SUM 500MG INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'GRASIL 25MG INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'GRASIL 50MGINJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'GRASIL 500MG INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'CARICEF 400MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'CARICEF SYP', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'CARICEF-DS SYP', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'SYP' },
  { name: 'MABIL INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'DICLORAN INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'D-TRES INJ 1S', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'D-TRES INJ 5S', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'ITAGLIP 50/500MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'MOFEST 400MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'MOVAX 2MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NOVIDATE 250MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NOVIDATE 500MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NOVIDATE INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'OXIDIL 1G INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'OXIDIL 500MG INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'OXIDIL 250MG INJ', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'INJ' },
  { name: 'MONTIKA 10MG TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NEO SEDIL TAB', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NOVATEPH 20MG CAP', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'NOVATEPH 40MG CAP', company: 'SAMI PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'T-DAY TAB', company: 'SANDOZ PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NUBEROL FORT TAB', company: 'SEREAL PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'VITRUM TAB', company: 'SEREAL PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'TRAMAL CAP', company: 'SEREAL PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'TRAMAL -SR CAP', company: 'SEREAL PHARMA', discount: null, saleDiscount: 0, type: 'CAP' },
  { name: 'NEXUM 0.25 TAB', company: 'STAND PHARMA', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'NEXUM 0.5 TAB', company: 'STAND PHARMA', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'NEXUM 1G TAB', company: 'STAND PHARMA', discount: null, saleDiscount: 1, type: 'TAB' },
  { name: 'BROLITE TAB', company: 'STAND PHARMA', discount: null, saleDiscount: 3, type: 'TAB' },
  { name: 'HIGH-C SAC', company: 'WERRIC PHARMA', discount: null, saleDiscount: 4, type: 'SAC' },
  { name: 'NEW DAY 5/80MG TAB', company: 'WERRIC PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'NEWDAY 5/160MG TAB', company: 'WERRIC PHARMA', discount: null, saleDiscount: 0, type: 'TAB' },
  { name: 'DURAGESIC TAB', company: 'WERRIC PHARMA', discount: null, saleDiscount: 2, type: 'TAB' },
  { name: 'FAMILA INJ', company: 'ZAFA PHARMA', discount: null, saleDiscount: 3, type: 'INJ' },
  { name: 'FAMILA TAB', company: 'ZAFA PHARMA', discount: null, saleDiscount: 4, type: 'TAB' },
  { name: 'FLORAMAX CAP', company: 'ZAFA PHARMA', discount: null, saleDiscount: 4, type: 'CAP' },
  { name: 'CLOBIDERM LOTION', company: 'ACTO LABORATORIES', discount: null, saleDiscount: null, type: 'LOTION' },
  { name: 'CLOBIDERM-NN OINTMENT', company: 'ACTO LABORATORIES', discount: null, saleDiscount: null, type: 'OINTMENT' },
  { name: 'PYDROQUIN PLUS', company: 'ACTO LABORATORIES', discount: null, saleDiscount: null, type: 'OTHER' },
  { name: 'XYLOR TAB', company: 'AUSTIN PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'CIPROXIN 250MG TAB', company: 'BAYAR PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'CIPROXIN 500MG TAB', company: 'BAYAR PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'CRESTAT 10MG TAB', company: 'C.C.L PHARMACEUTICALS', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'CIROLIN SYP', company: 'CHAS-A MENDOZA', discount: null, saleDiscount: null, type: 'SYP' },
  { name: 'VITA-6 TAB', company: 'CHAS-A MENDOZA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'ANTIAL TAB', company: 'CONTINENTIAL PHARMA-F-E', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'ST MOM TAB', company: 'DISPENSING ITEMS', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'TEMEY 0.4MG TAB', company: 'DISPENSING ITEMS', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'UNIPEP 10MG TAB', company: 'DISPENSING ITEMS', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'ACYLEX 200MG TAB', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'AZOBAR 250MG', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: null, type: 'OTHER' },
  { name: 'CLARION 125MG SYP', company: 'FEROZSONS LABORATORIES', discount: null, saleDiscount: null, type: 'SYP' },
  { name: 'ZAVOGET 10MG TAB', company: 'GETZ PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'NILBIN INJ', company: 'GLOBAL PHARMACEUTICALS', discount: null, saleDiscount: null, type: 'INJ' },
  { name: 'LORNEX 8MG TAB', company: 'HARBAL MIX MEDICINE', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'XENGLUMET 12.5/1000MG', company: 'HILTON PHARMA', discount: null, saleDiscount: null, type: 'OTHER' },
  { name: 'XENGLUMET 12.5/850MG', company: 'HILTON PHARMA', discount: null, saleDiscount: null, type: 'OTHER' },
  { name: 'XENGLUMET 12.5/500MG', company: 'HILTON PHARMA', discount: null, saleDiscount: null, type: 'OTHER' },
  { name: 'DYCLO-P TAB', company: 'INDUS PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'PROXIN 500MG TAB', company: 'MARTIN DOW PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'LEVOPRIDE 25MG TAB', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'LEVOPRIDE 50MG TAB', company: 'P.D.H LABORATORIES', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'ZATOFIN TAB', company: 'HILTON PHARMA', discount: null, saleDiscount: null, type: 'TAB' },
  { name: 'SANGOBIAN CAP', company: 'MARCK MARKER', discount: null, saleDiscount: null, type: 'CAP' },
];